pom.xml
src/main/java/org/kiwiproject/registry/client/RegistryClient.java
src/main/java/org/kiwiproject/registry/config/ServiceInfo.java
src/main/java/org/kiwiproject/registry/exception/RegistrationException.java
src/main/java/org/kiwiproject/registry/management/RegistrationManager.java
src/main/java/org/kiwiproject/registry/management/dropwizard/RegistrationLifecycleListener.java
src/main/java/org/kiwiproject/registry/model/Port.java
src/main/java/org/kiwiproject/registry/model/ServiceInstance.java
src/main/java/org/kiwiproject/registry/model/ServicePaths.java
src/main/java/org/kiwiproject/registry/server/NoopRegistryService.java
src/main/java/org/kiwiproject/registry/server/RegistryService.java
src/test/java/org/kiwiproject/registry/client/RegistryClientTest.java
src/test/java/org/kiwiproject/registry/config/ServiceInfoTest.java
src/test/java/org/kiwiproject/registry/exception/RegistrationExceptionTest.java
src/test/java/org/kiwiproject/registry/management/RegistrationManagerTest.java
src/test/java/org/kiwiproject/registry/management/dropwizard/RegistrationLifecycleListenerTest.java
src/test/java/org/kiwiproject/registry/model/ServiceInstanceTest.java
src/test/java/org/kiwiproject/registry/model/ServicePathsTest.java
src/test/java/org/kiwiproject/registry/server/NoopRegistryServiceTest.java
src/test/java/org/kiwiproject/registry/test/util/StandardExceptionTests.java
src/test/java/org/kiwiproject/registry/util/BlankStringArgumentsProvider.java
src/test/java/org/kiwiproject/registry/util/ServiceInfoHelper.java

Add in base code for the library

---

src/main/java/org/kiwiproject/registry/eureka/config/EurekaConfig.java
src/main/java/org/kiwiproject/registry/eureka/config/EurekaRegistrationConfig.java
src/test/java/org/kiwiproject/registry/eureka/config/EurekaConfigTest.java
src/test/java/org/kiwiproject/registry/eureka/config/EurekaRegistrationConfigTest.java

* EurekaConfig contains the base config for connecting to Eureka servers
* EurekaRegistrationConfig is used for registering a service
Closes #8

Add Eureka configs

---

pom.xml
src/main/java/org/kiwiproject/registry/eureka/common/EurekaInstance.java
src/main/java/org/kiwiproject/registry/eureka/common/EurekaRestClient.java
src/test/java/org/kiwiproject/registry/eureka/common/EurekaInstanceTest.java
src/test/java/org/kiwiproject/registry/eureka/common/EurekaRestClientTest.java
src/test/java/org/kiwiproject/registry/util/ServiceInfoHelper.java

Add EurekaRestClient and EurekaInstance

---

src/main/java/org/kiwiproject/registry/eureka/common/EurekaInstance.java
src/main/java/org/kiwiproject/registry/eureka/server/EurekaRegistryService.java
src/test/java/org/kiwiproject/registry/eureka/common/EurekaInstanceTest.java
src/test/java/org/kiwiproject/registry/eureka/server/EurekaRegistryServiceIntegrationTest.java
src/test/java/org/kiwiproject/registry/util/ServiceInfoHelper.java

Add EurekaRegistryService

---

src/main/java/org/kiwiproject/registry/eureka/server/EurekaRegistryService.java
src/main/java/org/kiwiproject/registry/server/NoopRegistryService.java
src/main/java/org/kiwiproject/registry/server/RegistryService.java
src/test/java/org/kiwiproject/registry/eureka/server/EurekaRegistryServiceIntegrationTest.java
src/test/java/org/kiwiproject/registry/server/NoopRegistryServiceTest.java

* Update NoopRegistryService impl for new method
* Update EurekaRegistryService impl for new method
Closes #14

Add update status call to RegistryService

---

src/main/java/org/kiwiproject/registry/client/RegistryClient.java
src/main/java/org/kiwiproject/registry/consul/client/ConsulRegistryClient.java
src/main/java/org/kiwiproject/registry/consul/server/ConsulRegistryService.java
src/main/java/org/kiwiproject/registry/eureka/client/EurekaRegistryClient.java
src/main/java/org/kiwiproject/registry/management/dropwizard/RegistrationLifecycleListener.java
src/main/java/org/kiwiproject/registry/model/Port.java
src/main/java/org/kiwiproject/registry/util/Ports.java
src/main/java/org/kiwiproject/registry/util/ServiceInstancePaths.java
src/test/java/org/kiwiproject/registry/consul/client/ConsulRegistryClientTest.java

* Modify RegistryClient interface to include defaults for methods that are delegating
* Update ConsulRegistryService to add more metadata fields
* Add scheme to the Port model so that secure and not secure have https or http defined

Add ConsulRegistryClient and accompanying tests

---

pom.xml

This will probably fail initially until embedded-eureka gets indexed

Upgrade embedded-eureka to 0.3.0

---

src/main/java/org/kiwiproject/registry/eureka/common/EurekaRestClient.java

Add timeout to Client when using no-args constructor in EurekaRestClient

---

pom.xml

Upgrade embedded-eureka to 0.3.1

---

pom.xml

* kiwi -> 0.14.0
* kiwi-test -> 0.9.0
* embedded-eureka -> 0.4.0
* Removed temporary dependency exclusions

Upgrade kiwiproject dependencies

---

src/main/java/org/kiwiproject/registry/eureka/common/EurekaInstance.java
src/main/java/org/kiwiproject/registry/util/Ports.java
src/test/java/org/kiwiproject/registry/util/PortsTest.java

* Change Ports#findPort so that the argument order is PortType then
Security to be consistent with other places in this library
Fixes #56

Change argument order in Ports#findPort

---

src/main/java/org/kiwiproject/registry/client/ServiceInstanceFilter.java
src/main/java/org/kiwiproject/registry/management/dropwizard/RegistrationLifecycleListener.java

* Fixes in ServiceInstanceFilter and RegistrationLifecycleListener
Fixes #58

Fix several javadoc warnings

---

src/main/java/org/kiwiproject/registry/model/ServiceInstance.java
src/test/java/org/kiwiproject/registry/model/ServiceInstanceTest.java
src/test/java/org/kiwiproject/registry/util/ServiceInfoHelper.java

Copy metadata from ServiceInfo in ServiceInstance#fromServiceInfo

---

src/main/java/org/kiwiproject/registry/model/Port.java
src/test/java/org/kiwiproject/registry/model/PortTest.java

* isSecure()
* getScheme()
* isApplication()
* isAdmin()
Closes #80

Add convenience methods to Port

---

src/main/java/org/kiwiproject/registry/consul/config/ConsulConfig.java
src/main/java/org/kiwiproject/registry/eureka/config/EurekaConfig.java
src/test/java/org/kiwiproject/registry/consul/config/ConsulRegistrationConfigTest.java
src/test/java/org/kiwiproject/registry/eureka/config/EurekaConfigTest.java

Add includeNativeData to ConsulConfig and EurekaConfig

---

src/main/java/org/kiwiproject/registry/consul/client/ConsulRegistryClient.java
src/main/java/org/kiwiproject/registry/eureka/common/EurekaInstance.java
src/main/java/org/kiwiproject/registry/eureka/server/EurekaRegistryService.java
src/main/java/org/kiwiproject/registry/model/ServiceInstance.java
src/test/java/org/kiwiproject/registry/consul/client/ConsulRegistryClientTest.java
src/test/java/org/kiwiproject/registry/eureka/common/EurekaInstanceTest.java
src/test/java/org/kiwiproject/registry/model/ServiceInstanceTest.java

Add upSince to ServiceInstance

---

src/main/java/org/kiwiproject/registry/consul/client/ConsulRegistryClient.java
src/main/java/org/kiwiproject/registry/eureka/client/EurekaParser.java
src/main/java/org/kiwiproject/registry/eureka/client/EurekaRegistryClient.java
src/main/java/org/kiwiproject/registry/eureka/common/EurekaInstance.java
src/main/java/org/kiwiproject/registry/eureka/server/EurekaRegistryService.java
src/main/java/org/kiwiproject/registry/model/NativeRegistryData.java
src/main/java/org/kiwiproject/registry/model/ServiceInstance.java
src/test/java/org/kiwiproject/registry/consul/client/ConsulRegistryClientTest.java
src/test/java/org/kiwiproject/registry/eureka/common/EurekaInstanceTest.java
src/test/java/org/kiwiproject/registry/model/ServiceInstanceTest.java

Add native registry information if configured to do so

---

src/main/java/org/kiwiproject/registry/consul/client/ConsulRegistryClient.java
src/main/java/org/kiwiproject/registry/eureka/common/EurekaInstance.java
src/test/java/org/kiwiproject/registry/consul/client/ConsulRegistryClientTest.java
src/test/java/org/kiwiproject/registry/eureka/common/EurekaInstanceTest.java

Add registryType to metadata

---

src/main/java/org/kiwiproject/registry/consul/server/ConsulHelpers.java
src/main/java/org/kiwiproject/registry/consul/server/ConsulRegistryService.java
src/test/java/org/kiwiproject/registry/consul/server/ConsulHelpersTest.java

Add ConsulHelpers

---

src/main/java/org/kiwiproject/registry/model/Port.java
src/test/java/org/kiwiproject/registry/model/PortTest.java

* Use Lombok to generate the toString() method in Port
Closes #99

Add simple toString() to Port

---

pom.xml
src/main/java/org/kiwiproject/registry/eureka/client/EurekaParser.java
src/test/resources/EurekaParserTest/eureka-response-as-all-lists.json
src/test/resources/EurekaParserTest/eureka-response-as-all-maps.json
src/test/resources/EurekaParserTest/eureka-response-as-application-list-instance-map.json
src/test/resources/EurekaParserTest/eureka-response-as-application-map-instance-list.json

Fix Eureka status url from `statusUrl` to `statusPageUrl`

---

src/main/java/org/kiwiproject/registry/eureka/server/EurekaHeartbeatSender.java
src/test/java/org/kiwiproject/registry/eureka/server/EurekaHeartbeatSenderTest.java

* Include more information about exceptions when heartbeats fail,
specifically the exception message, the root cause, and root cause
message
* Since this specific code wasn't tested (since our test logback.xml
uses TRACE level logging), add "tests" to ensure that logging code
won't throw exceptions even when given invalid arguments. The "tests"
therefore don't actually verify the log statements' exact contents.
Closes #150

Add more information in logs when Eureka heartbeats fail

---

src/test/java/org/kiwiproject/registry/consul/server/ConsulRegistryServiceIntegrationTest.java
src/test/java/org/kiwiproject/registry/eureka/server/EurekaRegistryServiceIntegrationTest.java
src/test/java/org/kiwiproject/registry/util/ServiceInfoHelper.java

* Rename buildTestServiceinfoWithHostName to change 'Serviceinfo' to
'ServiceInfo'. New name: buildTestServiceInfoWithHostName

Fix method name in ServiceInfoHelper

---

src/main/java/org/kiwiproject/registry/eureka/client/EurekaRegistryClient.java

* Extract duplicate code in EurekaRegistryClient into a private
static helper method (parseEurekaInstances)

Extract duplicate code into method to parse Eureka responses

---

src/test/java/org/kiwiproject/registry/eureka/client/EurekaRegistryClientTest.java

Remove the Mockito spies from EurekaRegistryClient in the
EurekaRegistryClientTest. It turns out they were not actually doing
anything at all and thus were not changing the WaitStrategy in the retry
tests. The reason is that EurekaRegistryClient's constructor creates
a KiwiRetryer once, and uses the default wait strategy (which in our
case is an exponential strategy). So, after the EurekaRegistryClient has
been created, getWaitStrategy() is never called again and thus the
Mockito stubbing had no effect whatsoever!
Change the top-level setUp so that it creates a "real" instance of
EurekaRegistryClient, and change the setUp in the WithRetry nested test
class so that it overrides the getWaitStrategy method to return a
"no wait" strategy. This makes the retry tests way faster, e.g. about
4-5 …

Remove useless Mockito spies from EurekaRegistryClientTest

---

src/test/java/org/kiwiproject/registry/eureka/client/EurekaRegistryClientTest.java

Add tests to ensure we cover the (possible but unlikely) situations
inside EurekaRegistryClient#temporaryServerSideStatusCodes in which:
* The exception is not a ServerErrorException but instead has a
ServerErrorException as a root cause
* The exception thrown is some other type of exception, e.g. a JAX-RS
ProcessingException
The existing tests did not cover those scenarios.

Add additional tests for EurekaRegistryClient

---

src/main/java/org/kiwiproject/registry/eureka/config/EurekaConfig.java

Make registryUrls field private in EurekaConfig

---

.github/workflows/build.yml

Update build to support java 11 and 17

---

pom.xml

Use Testcontainers BOM

---

src/main/java/org/kiwiproject/registry/consul/config/ConsulConfig.java

Deprecate domainOverride in ConsulConfig

---

src/main/java/org/kiwiproject/registry/client/NoOpRegistryClient.java
src/test/java/org/kiwiproject/registry/client/NoOpRegistryClientTest.java

Add "no-op" implementation of RegistryClient

---

src/main/java/org/kiwiproject/registry/client/MultiRegistryClient.java
src/test/java/org/kiwiproject/registry/client/MultiRegistryClientTest.java

* Add MultiRegistryClient
Closes  #314

Add multi-registry RegistryClient implementation

---

src/main/java/org/kiwiproject/registry/eureka/common/EurekaResponseParser.java
src/main/java/org/kiwiproject/registry/eureka/server/EurekaHeartbeatSender.java
src/main/java/org/kiwiproject/registry/model/Port.java
src/main/java/org/kiwiproject/registry/util/ServiceInstancePaths.java

* Replace Nullable with equivalent from Checker
Closes #320

Replace JSR 305 annotations

---

pom.xml

Lock versions of kiwi, kiwi-test, and retrying-again

---

src/main/java/org/kiwiproject/registry/consul/server/ConsulRegistryService.java
src/main/java/org/kiwiproject/registry/eureka/server/EurekaRegistryService.java

* Add "type" to the SimpleRetryer objects in ConsulRegistryService and EurekaRegistryService
Closes #324

Add "type" to the SimpleRetryer objects

---

src/main/java/org/kiwiproject/registry/consul/client/ConsulRegistryClient.java
src/main/java/org/kiwiproject/registry/consul/config/ConsulConfig.java
src/main/java/org/kiwiproject/registry/consul/server/ConsulRegistryService.java
src/test/java/org/kiwiproject/registry/consul/client/ConsulRegistryClientTest.java
src/test/java/org/kiwiproject/registry/consul/server/ConsulRegistryServiceIntegrationTest.java

Remove domainOverride functionality from Consul client and server

---

src/test/java/org/kiwiproject/registry/consul/client/ConsulRegistryClientTest.java
src/test/java/org/kiwiproject/registry/consul/server/ConsulRegistryServiceIntegrationTest.java
src/test/java/org/kiwiproject/registry/eureka/common/EurekaRestClientTest.java
src/test/java/org/kiwiproject/registry/eureka/config/EurekaConfigTest.java
src/test/java/org/kiwiproject/registry/eureka/util/EurekaTestDataHelper.java

* Make fields local vars in the setup of ConsulRegistryClientTest and ConsulRegistryServiceIntegrationTest
* Use try-with-resources in EurekaRestClientTest & EurekaTestDataHelper
* Use method reference in EurekaConfigTest
* Use !isEmpty() on list instead of size() > 0

Misc code cleanup

---

src/test/java/org/kiwiproject/registry/consul/util/ConsulTestcontainers.java

Update Consul testcontainer from 1.15 to 1.16.1

---

src/test/java/org/kiwiproject/registry/eureka/client/EurekaRegistryClientTest.java
src/test/java/org/kiwiproject/registry/eureka/common/EurekaRestClientTest.java
src/test/java/org/kiwiproject/registry/eureka/server/EurekaRegistryServiceIntegrationTest.java

Temporarily disable Eureka integration tests (due to Docker container issue)
