src/main/java/org/kiwiproject/registry/model/ServiceInstance.java
src/test/java/org/kiwiproject/registry/model/ServiceInstanceTest.java

There was an issue with Javadoc and Lombok generated builders because
javadoc does not process annotations first and thus `fromServiceInfo`'s
return value of `ServiceInstanceBuilder` caused javadoc generation
failures.
This changes the method to return an actual ServiceInstance and in
order to still allow for setting the instanceId and status, this commit
adds `@With` annotations for those fields.

Change `fromServiceInfo` return value to ServiceInstance

---

src/main/java/org/kiwiproject/registry/consul/client/ConsulRegistryClient.java
src/main/java/org/kiwiproject/registry/eureka/common/EurekaInstance.java
src/main/java/org/kiwiproject/registry/management/dropwizard/RegistrationLifecycleListener.java
src/main/java/org/kiwiproject/registry/model/Port.java
src/main/java/org/kiwiproject/registry/util/Ports.java
src/test/java/org/kiwiproject/registry/eureka/common/EurekaInstanceTest.java
src/test/java/org/kiwiproject/registry/management/dropwizard/RegistrationLifecycleListenerTest.java
src/test/java/org/kiwiproject/registry/model/PortTest.java
src/test/java/org/kiwiproject/registry/util/PortsTest.java
src/test/java/org/kiwiproject/registry/util/ServiceInfoHelper.java
src/test/java/org/kiwiproject/registry/util/ServiceInstancePathsTest.java

* Add Port.of(number, type, security) factory method
* Change Port.builder() usages with Port.of
* Add imports for Port.PortType and Port.Security to make code cleaner
* Fix deprecation warnings in EurekaInstanceTest on the
isEqualToComparingFieldByField method; use usingRecursiveComparison
instead
Fixes #47

Add Port#of factory method

---

src/main/java/org/kiwiproject/registry/model/Port.java
src/test/java/org/kiwiproject/registry/model/PortTest.java

* Switch to "secure by default" in Security.fromScheme
Fixes #48

Change Security#fromScheme to return SECURE when argument is invalid

---

src/main/java/org/kiwiproject/registry/consul/server/ConsulRegistryService.java
src/main/java/org/kiwiproject/registry/management/dropwizard/RegistrationLifecycleListener.java
src/main/java/org/kiwiproject/registry/util/ServiceInstancePaths.java
src/test/java/org/kiwiproject/registry/util/ServiceInstancePathsTest.java

* Add leniency when handling paths in urlForPath. It now handles null,
trims leading and trailing whitespace, and prepends a slash if
necessary
* Import PortType so we don't have Port.PortType all over the place
Fixes #62

Fix path handling in ServiceInstancePaths#urlForPath

---

src/main/java/org/kiwiproject/registry/eureka/client/EurekaParser.java
src/main/java/org/kiwiproject/registry/eureka/common/EurekaInstance.java
src/test/java/org/kiwiproject/registry/eureka/client/EurekaParserTest.java
src/test/resources/EurekaParserTest/eureka-response-as-all-lists.json
src/test/resources/EurekaParserTest/eureka-response-as-all-maps.json
src/test/resources/EurekaParserTest/eureka-response-as-application-list-instance-map.json
src/test/resources/EurekaParserTest/eureka-response-as-application-map-instance-list.json

* EurekaParser#buildInstance should set the admin port from either the
status or health check URL
* Minor refactoring in EurekaInstance; rename methods to end with the
suffix "OrNull" for clarity
* Change the health check URLs in the sample test data to be
/healthcheck (instead of /healthCheck) since that's our normal path
Fixes #66

Set the admin port from Eureka response in EurekaParser

---

src/main/java/org/kiwiproject/registry/config/ServiceInfo.java
src/test/java/org/kiwiproject/registry/config/ServiceInfoTest.java

* Add ServiceInfo#getMetadata as default method returning empty Map
* Reformat javadoc on getCommitRef() to wrap before 120 char limit
Closes #74

Add getMetadata() to ServiceInfo with default implementation

---

src/main/java/org/kiwiproject/registry/model/Port.java
src/main/java/org/kiwiproject/registry/model/ServiceInstance.java
src/test/java/org/kiwiproject/registry/model/ServiceInstanceTest.java

* Add getApplicationPort and getAdminPort to ServiceInstance
* Make Port be a Lombok value class instead of just having getters and
toString()
Closes #101

Helper methods to get application and admin Port from ServiceInstance

---

src/main/java/org/kiwiproject/registry/eureka/config/EurekaConfig.java
src/main/java/org/kiwiproject/registry/eureka/config/ListToCsvStringDeserializer.java
src/test/java/org/kiwiproject/registry/eureka/config/EurekaConfigTest.java
src/test/resources/EurekaConfigTest/sample-config-csv-urls.json
src/test/resources/EurekaConfigTest/sample-config-csv-urls.yml
src/test/resources/EurekaConfigTest/sample-config-list-of-one-url.yml
src/test/resources/EurekaConfigTest/sample-config-list-of-urls.json
src/test/resources/EurekaConfigTest/sample-config-list-of-urls.yml

* Add setRegistryUrls(List<String>) in EurekaConfig
* Add "default" setRegistryUrls(String) in EurekaConfig because Lombok
no longer generates the setter once it sees that there already is one
* Add ListToCsvStringDeserializer, a custom Jackson JsonDeserializer to
allow de-serialization from either a CSV string or a list of strings
* Add a bunch of YAML and JSON test resources to support testing the
various de-serialization cases
Closes #103

Allow setting List of Eureka server URLS on EurekaConfig

---

pom.xml
src/main/java/org/kiwiproject/registry/eureka/client/EurekaRegistryClient.java
src/test/java/org/kiwiproject/registry/eureka/client/EurekaRegistryClientTest.java
src/test/java/org/kiwiproject/registry/eureka/common/EurekaRestClientTest.java
src/test/java/org/kiwiproject/registry/eureka/server/EurekaRegistryServiceIntegrationTest.java

* Fix the compile errors that occurred when updating to embedded-eureka
0.12.0, specifically registeredApplications() was renamed to
getRegisteredApplications() and cleanupApps() method was renamed to
clearRegisteredApps().
* Switch from re-retrying library to retrying-again since that changed
in kiwi 0.21.0, and fix various breaking changes such as
KiwiRetryerPredicates now using Exception not Throwable, and using
the Java/JDK Predicate instead of Guava's.
* Fix breaking test in EurekaRegistryClientTest due to the switch to
retrying-again; Retryer no longer throws an ExecutionException so
the cause of the KiwiRetryerException should be RetryException
* Use the helper methods now in EurekaServerExtension as of
embedded-eureka 0.12.0 to avoid all the repeated calls to …

Fix compile errors due to embedded-eureka updates; misc cleanup

---

src/main/java/org/kiwiproject/registry/eureka/client/EurekaParser.java
src/test/resources/EurekaParserTest/eureka-response-as-all-lists.json
src/test/resources/EurekaParserTest/eureka-response-as-all-maps.json
src/test/resources/EurekaParserTest/eureka-response-as-application-list-instance-map.json
src/test/resources/EurekaParserTest/eureka-response-as-application-map-instance-list.json

* Fix Eureka status url from `statusUrl` to `statusPageUrl`
Closes #113

Fix Eureka status url from `statusUrl` to `statusPageUrl` (#115)

---

src/main/java/org/kiwiproject/registry/eureka/server/EurekaRegistryService.java

* In the updateStatus method, rename the 'instanceToUnregister' local
variable to 'instanceToUpdate'

Rename incorrectly named local var in EurekaRegistryService

---

src/main/java/org/kiwiproject/registry/management/dropwizard/RegistrationLifecycleListener.java

Change RegistrationLifecycleListener to implement Lifecycle.Listener
instead of extending AbstractLifeCycle.AbstractLifeCycleListener, which
is deprecated.

Sonar: fix deprecated code usage in RegistrationLifecycleListener

---

pom.xml
src/main/java/org/kiwiproject/registry/eureka/client/EurekaRegistryClient.java
src/main/java/org/kiwiproject/registry/eureka/common/EurekaRestClient.java
src/main/java/org/kiwiproject/registry/eureka/config/EurekaRegistrationConfig.java
src/main/java/org/kiwiproject/registry/eureka/server/EurekaHeartbeatSender.java
src/main/java/org/kiwiproject/registry/eureka/server/EurekaRegistryService.java
src/test/java/org/kiwiproject/registry/eureka/client/EurekaRegistryClientTest.java
src/test/java/org/kiwiproject/registry/eureka/common/EurekaRestClientTest.java
src/test/java/org/kiwiproject/registry/eureka/server/EurekaHeartbeatSenderTest.java
src/test/java/org/kiwiproject/registry/eureka/server/EurekaRegistryServiceIntegrationTest.java
src/test/java/org/kiwiproject/registry/eureka/server/EurekaRegistryServiceTest.java
src/test/java/org/kiwiproject/registry/eureka/util/EurekaTestDataHelper.java
src/test/java/org/kiwiproject/registry/util/ResponseMock.java
src/test/resources/eureka-server/Dockerfile
src/test/resources/eureka-server/config.properties
src/test/resources/eureka-server/eureka-client-test.properties
src/test/resources/eureka-server/eureka-server-test.properties

Replace embedded eureka with testcontainers running eureka in a container
* I did have to remove a few tests related to heartbeats as I don't have as much insight into the interworkings of Eureka this way and expecting things to happen in a parallel world is very challenging.
* We currently have the eureka war in the test/resources.  We could set the Dockerfile to download the war but it will slow down the tests even more
* Tests are slower now which makes sense, it has to spin up a container
* One other option would be to release a new eureka container under kiwi project's domain and use that.
Closes #234

Switch to test containers

---

src/test/java/org/kiwiproject/registry/consul/client/ConsulRegistryClientTest.java
src/test/java/org/kiwiproject/registry/consul/server/ConsulRegistryServiceIntegrationTest.java

* The HostAndPort class is no longer marked as "beta" in Guava, so
the SuppressWarnings annotations can be removed
* Add a TODO regarding the IntelliJ warning that ConsulExtension can
be static.

Remove redundant UnstableApiUsage warning suppression annotations

---

src/test/java/org/kiwiproject/registry/consul/util/ConsulStarterHelper.java

The downloadPath local variable can be re-used instead of doing the
same Path.of(downloadLocation) in #buildStarterConfigWithEnvironment

Code cleanup: use existing local variable in ConsulStarterHelper

---

src/test/java/org/kiwiproject/registry/eureka/client/EurekaRegistryClientTest.java
src/test/java/org/kiwiproject/registry/eureka/common/EurekaRestClientTest.java
src/test/java/org/kiwiproject/registry/eureka/server/EurekaRegistryServiceIntegrationTest.java
src/test/java/org/kiwiproject/registry/eureka/util/EurekaTestDataHelper.java

* Make the static GenericContainer fields in tests final too
* Rename the GenericContainer fields with ALL_UPPERCASE to be idiomatic
* Suppress generics warnings on GenericContainer; there's nothing we
can parameterize it with that makes sense, so ignore
* Make EurekaTestDataHelper#eurekaUrl accept GenericContainer<?> to
make the raw types warning go away.

Make static GenericContainer fields final in tests

---

src/main/java/org/kiwiproject/registry/eureka/server/EurekaHeartbeatSender.java
src/main/java/org/kiwiproject/registry/eureka/server/EurekaRegistryService.java

* Add a 'finally' block in EurekaHeartbeatSender#run that closes the
response. KiwiResponses#closeQuietly ignores null arguments so there
is no need for a guard around the call.
* In EurekaRegistryService#registerWithEureka, refactor the code to be
more clear. IntelliJ was complaining that we're not using
try-with-resources for the Response. Change code to use
Optionals#ifPresentOrElseThrow so that the action for success and
failure cases are clear. Also, extract code to read entity "safely"
into a helper method and call that. Reading the entity ensures the
response is closed.
* In EurekaRegistryService#waitForInstanceToBeRegistered, rename
'response' to 'responseOptional' to make it clear the type is
really an Optional containing a Response. Do the same in updateStatus
and …

Ensure Eureka responses are always closed

---

src/main/java/org/kiwiproject/registry/eureka/client/EurekaRegistryClient.java
src/main/java/org/kiwiproject/registry/eureka/config/EurekaConfig.java
src/test/java/org/kiwiproject/registry/eureka/config/EurekaConfigTest.java

* Add retryProcessingLogLevel and retryExceptionLogLevel to EurekaConfig
* Pass the configured log levels to the KiwiRetryer in EurekaRegistryClient
Closes #275

Add ability to configure Eureka HTTP call retry log levels

---

src/main/java/org/kiwiproject/registry/consul/client/ConsulRegistryClient.java
src/test/java/org/kiwiproject/registry/consul/client/ConsulRegistryClientTest.java

I know why CodeQL is saying to handle NumberFormatExceptions, and it is probably better to throw IllegalStateException, but it is definitely annoying to try/catch all these. Maybe add some utilities to kiwi...
Fixes #293
Fixes #294

Catch NumberFormatExceptions; rethrow as IllegalStateException

---

src/main/java/org/kiwiproject/registry/model/ServiceInstance.java
src/main/java/org/kiwiproject/registry/model/ServicePaths.java

CodeQL complained about default toString() implementations, but these classes can and probably should be "Value" classes with equals, hashCode, and toString. Use Lombok Value annotation to make this easy. Remove "private" and "final" modifiers since Lombok does that for us.
Fixes #295

Make ServiceInstance and ServicePaths Value classes

---

src/test/java/org/kiwiproject/registry/consul/util/ConsulTestcontainers.java

This is because of the notice posted to hub.docker.com:
Upcoming in Consul 1.16, we will stop publishing official Dockerhub images and publish only our Verified Publisher images. Users of Docker images should pull from hashicorp/consul instead of consul. Verified Publisher images can be found at
https://hub.docker.com/r/hashicorp/consul.

Update Docker image name for Consul to hashicorp/consul:1.15

---

.github/workflows/build.yml
.github/workflows/codeql.yml
pom.xml
src/main/java/org/kiwiproject/registry/eureka/client/EurekaRegistryClient.java
src/main/java/org/kiwiproject/registry/eureka/common/EurekaRestClient.java
src/main/java/org/kiwiproject/registry/eureka/config/EurekaConfig.java
src/main/java/org/kiwiproject/registry/eureka/config/EurekaRegistrationConfig.java
src/main/java/org/kiwiproject/registry/eureka/server/EurekaHeartbeatSender.java
src/main/java/org/kiwiproject/registry/eureka/server/EurekaRegistryService.java
src/test/java/org/kiwiproject/registry/eureka/client/EurekaRegistryClientTest.java
src/test/java/org/kiwiproject/registry/eureka/server/EurekaHeartbeatSenderTest.java
src/test/java/org/kiwiproject/registry/eureka/server/EurekaRegistryServiceTest.java
src/test/java/org/kiwiproject/registry/eureka/util/EurekaTestDataHelper.java
src/test/java/org/kiwiproject/registry/util/ResponseMock.java

* Bump version to 2.0.0-SNAPSHOT
* Bump kiwi-parent from 2.0.20 to 3.0.1
* Bump kiwi-bom from 1.1.1 to 2.0.0
* Bump kiwi libraries to next major version
* Update build for JDK 17 and 20
* Update CodeQL workflow to use JDK 17
* Fix Dropwizard package changes
* Refactor from javax to jakarta namespace for Jakarta EE 9

Update parent POM and BOM for JDK 17 and major library updates

---

src/main/java/org/kiwiproject/registry/client/MultiRegistryClient.java
src/main/java/org/kiwiproject/registry/client/ServiceInstanceFilter.java
src/main/java/org/kiwiproject/registry/consul/client/ConsulRegistryClient.java
src/main/java/org/kiwiproject/registry/consul/server/ConsulRegistryService.java
src/main/java/org/kiwiproject/registry/eureka/client/EurekaRegistryClient.java
src/main/java/org/kiwiproject/registry/eureka/common/EurekaInstance.java
src/main/java/org/kiwiproject/registry/eureka/common/EurekaResponseParser.java
src/test/java/org/kiwiproject/registry/consul/server/ConsulRegistryServiceIntegrationTest.java

Rules fixed:
* java:S6204: "Stream.toList()" method should be used instead of "collectors" when unmodifiable list needed
* java:S6201 - Pattern Matching for "instanceof" operator should be used instead of simple "instanceof" + cast
Even where we are collecting toList(), I replaced these as well, since we really want to be returning immutable (unmodifiable) lists anyway.

Sonar fixes for update to JDK 17

---

src/main/java/org/kiwiproject/registry/util/Ports.java
src/test/java/org/kiwiproject/registry/util/PortsTest.java

* Add findOnlyApplicationPort to find the single application port
* Add findApplicationPorts to find only application ports
* Add findOnlyAdminPort to find the single admin port
* Add findAdminPorts to find only admin ports
* Add findPorts to find ports of a specific type
* Add additional test for findPort method to cover all branches
Closes #411

Add port filtering methods to Ports

---

src/main/java/org/kiwiproject/registry/util/Ports.java

* Change javadoc to say there must be exactly one application/admin port in the "findOnly" methods

Fix javadoc in Ports

---

src/test/java/org/kiwiproject/registry/client/NoOpRegistryClientTest.java
src/test/java/org/kiwiproject/registry/eureka/config/EurekaConfigTest.java
src/test/java/org/kiwiproject/registry/eureka/server/EurekaRegistryServiceIntegrationTest.java

* Deprecated code should not be used java:S1874
* "Stream.toList()" method should be used instead of "collectors" when an unmodifiable list is needed java:S6204
* Local variables should not shadow class fields java:S1117

Sonar cleanup
